INSERT INTO `omraade` (`fylke`, `omr_navn`) VALUES
('Hordaland, Sogn og Fjordane, Buskerud', 'Rallarvegen');

INSERT INTO `lokasjon` (`stad`, `adresse`, `omr_id`, `hente_levere`, `lager`, `postnummer`) VALUES
('Haugastøl', 'Haugaveien 25', 1, 1, 1, 3595),
('Geilo', 'Geilovegen 23', 1, 1, 0, 5530),
('Finse', 'Sykkelvegen 31', 1, 1, 0, 5533),
('Voss', 'Vossafår 60', 1, 1, 0, 5540),
('Myrdal', 'Sykkelgata 39', 1, 1, 0, 5560),
('Flåm', 'Hovedgata 32', 1, 1, 0, 5402);

INSERT INTO `ansatt` (`avdeling`, `fnavn`, `enavn`, `tlf`, `epost`, `omr_id`, `brukernavn`, `passord`) VALUES
('admin', 'Malin', 'Kvamme', 97356373, 'malin.kvamme@bra.no', 1, 'makvam', '$2a$10$72I.Hx8PqQ2uCV4qTYG74u8BTpr84aGw4AvTlZ3jInsFCX1onTcLy'),
('admin', 'Oddbjørn', 'Eriksen', 65299107, 'oddbjorn.eriksen@bra.no', 1, 'odderiks', '$2a$10$pa6GbN3/6ba/5uL4NC0bG.aHlfRS9lrhhbrWuqSlGJoLx2ItbF9gq'),
('salg', 'Kathrin ', 'Strand', 66096729, 'kathrin.strand@bra.no', 1, 'kathstrand', '$2a$10$.iw05bIMFEpNckAbNJVvZesQL4UPVmOnSgC6.ItzwnYXAD9f4/j5S'),
('salg', 'Mahad', 'Nguyen', 93098303, 'mahad.nguyen@bra.no', 1, 'mahnguyen', '$2a$10$1b/iJgMtFmSfZL5E8/jEG.TO10g8ghcsCMTZ6hUfLC3OvNfM1KV.e'),
('salg', 'Jimmy', 'Weaver', 90266464, 'jimmy.weaver@bra.no', 1, 'jimweav', '$2a$10$O08k2FJz1fCG08OvJs6j3OnDEY.FC5mxnVzAa0awLckFN3Zq4G6BC'),
('lager', 'Faiza', 'Cortes', 93846949, 'faiza.cortes@bra.no', 1, 'faizcor', '$2a$10$y2ygP/PMyeMt5o.54sFeYO8KKbwwy3jhTFr6BtHkycqrGULyRR6c.'),
('lager', 'Carl Gustaf', 'Åkerlund', 61512547, 'carl-gustaf.aakerlundh@bra.no', 1, 'carlgus', '$2a$10$NPBmVSdiC/aba7b1/S0s6ei3bEAIarh.j8CpLe.F8tqIvlVhKhNXC');

INSERT INTO `ikkekompatible` (`sykkeltype`, `utstyrtype`) VALUES
('Terreng', 'Vogn'),
('Terreng', 'Barnesete');

INSERT INTO `kunde` (`fnavn`, `enavn`, `tlf`, `epost`, `date_reg`) VALUES
('Ragnhild', 'Bakken', 85748509, 'ragnhild.bakken@sykkel.com', '2019-01-15'),
('Aimad', 'Janssens', 96836418, 'aimadjanssens@teleworm.us', '2019-02-10'),
('Mike E.', 'Andreasen', 61902133, 'mikeeandreasen@dayrep.com', '2019-03-10'),
('Florismart', 'Chassé', 185283076, 'florismartchasse@bike.fr', '2018-12-16'),
('Gustavo', 'Ferguson', 330392272, 'gustavoferguson@msn.com', '2019-01-28'),
('Ute', 'Köhler', 812143176, 'utekohler@msn.de', '2019-03-17'),
('Jürgen', 'Hoffmann', 927735112, 'jurgenhoffman@hotmail.de', '2019-03-31'),
('Ludvig', 'Arnesen', 41085148, 'ludvigarnesen@gmail.com', '2019-02-13'),
('Mia', 'Gulbrandsen', 41085148, 'miagulbrandsen@live.no', '2019-01-16'),
('Angelica', 'Helland', 99820782, 'angelicahelland@gmail.com', '2018-12-31'),
('Martinius', 'Kjelsrud', 46538616, 'martinius.sykkel@msn.no', '2019-04-09'),
('Morgan', 'Tran', 45019800, 'trangutten@live.no', '2019-04-01'),
('Mayu', 'Okano', 781121842, 'mayu.okano@msn.jp', '2019-04-09'),
('Kinichi', 'Nakahara', 782906014, 'nakahara.kinichi@live.jp', '2019-03-23'),
('Mushtaq Noori', 'Tannous', 792694226, 'mushtaqman@msn.ar', '2018-12-24'),
('Elina', 'Kattilakoski', 502368146, 'elinahorses@hotmail.fi', '2019-01-24'),
('Aurelio', 'Napolitani', 353832329, 'aurelioitalylove@msn.it', '2019-04-06'),
('Tiziana', 'Conti', 388450617, 'tizianaloveit@live.it', '2019-03-24'),
('Tiberio Bernal', 'Soliz', 679817725, 'solizbike@hotmail.es', '2018-12-01'),
('Kathy Solórzano', 'Corrales', 799920861, 'corrales@bikegirls.es', '2019-04-08'),
('Grzegorz', 'Kozlowski', 608317234, 'grezegors@polishfan.pl', '2019-02-24'),
('Sigurþór', 'Theódórsson', 4187015, 'sigurbor@msn.is', '2019-02-16'),
('Gerriëtte', 'van der Slik', 647915098, 'geriette@hotmail.nl', '2019-03-16'),
('Havanna', 'Andersson', 224340095, 'havanna@msn.se', '2019-04-01'),
('Mårten', 'Norberg', 227948500, 'maartennordberg@viktigtype.se', '2019-04-05'),
('Gunnhild', 'Testeren', 859847586, 'test@test.no', '2019-04-09'),
('jon', 'kanon', 1234, 'asdaf', '2019-04-09');

INSERT INTO `sykkel` (`rammenr`, `dekk_storrelse`, `type`, `bruker`, `status`, `girsystem`, `bremser`, `naavaerende_lokasjon`, `tilhoerende_lokasjon`, `raapris`) VALUES
('UR8O493A', 29.00, 'Terreng', 'Voksen', 'Tilgjengelig', '1x12', 'skive', 1, 1, 35),
('IR987LS9', 29.00, 'Terreng', 'Voksen', 'Tilgjengelg', '1x12', 'skive', 1, 1, 39),
('K9540S43', 27.50, 'Terreng', 'Voksen', 'Tilgjengelig', '3x7', 'skive', 1, 1, 30),
('IK9R9483', 29.00, 'Terreng', 'Voksen', 'Tilgjengelig', '3x7', 'kloss', 1, 1, 29),
('54985A9K', 26.00, 'Terreng', 'Barn', 'Tilgjengelig', '3x7', 'kloss', 1, 1, 22),
('549KRO94', 26.00, 'Terreng', 'Barn', 'Tilgjengelig', '3x7', 'skive', 1, 1, 25),
('584KR938', 28.00, 'Hybrid', 'Voksen', 'Tilgjengelig', '3x9', 'skive', 1, 1, 30),
('JG9583L9', 28.00, 'Hybrid', 'Voksen', 'Tilgjengelig', '2x8', 'skive', 1, 1, 40),
('KF9840O9', 28.00, 'Hybrid', 'Voksen', 'Tilgjengelig', '1x7', 'kloss', 1, 1, 32),
('9845KO9I', 28.00, 'Hybrid', 'Voksen', 'Tilgjengelig', '3x8', 'skive', 1, 1, 38),
('JRI49382', 24.00, 'Hybrid', 'Barn', 'tilgjengelig', '3x7', 'kloss', 1, 1, 20),
('K95839LP', 20.00, 'Hybrid', 'Barn', 'Tilgjengelig', '1x7', 'skive', 1, 1, 15),
('AG487GY9', 28.00, 'Racer', 'Voksen', 'Tilgjengelig', '3x7', 'kloss', 1, 1, 35),
('AGR948G6', 28.00, 'Racer', 'Voksen', 'Tilgjengelig', '2x11', 'skive', 1, 1, 40),
('JGU847U1', 20.00, 'Racer', 'Barn', 'Tilgjengelig', '1x7', 'kloss', 1, 1, 25),
('857HF94U', 26.00, 'Racer', 'Barn', 'Tilgjengelig', '3x7', 'skive', 1, 1, 20),
('JG84849A', 28.00, 'by', 'Voksen', 'Tilgjengelig', '1x7', 'kloss', 1, 1, 32),
('BV84N8AN', 28.00, 'by', 'Voksen', 'Tilgjengelig', '1x7', 'skive', 1, 1, 35),
('958AW998', 20.00, 'by', 'Barn', 'Tilgjengelig', '1x7', 'kloss', 1, 1, 19),
('KL49HR98', 26.00, 'by', 'Barn', 'Tilgjengelig', '1x7', 'skive', 1, 1, 20),
('XD37718A', 26.00, 'Racer', 'Voksen', 'Tilgjengelig', '3x8', 'skive', 1, 1, 35);

INSERT INTO `tallopplysning` (`type`, `verdi`) VALUES
('provisjon', 0.13);


INSERT INTO `tilleggsutstyr` (`type`, `status`, `beskrivelse`, `raapris`, `naavaerende_lokasjon`, `tilhoerende_lokasjon`) VALUES
('Hjelm', 'Tilgjengelig', 'Groove Plus MIPS er ideel for aktive mennesker og for daglig bruk. Hjelmen fungerer like godt på elsykkel, som på bysykkel. MRAS strammesystem for høy komfort. Voksen.', 10, 1, 1),
('Hjelm', 'Tilgjengelig', 'Groove Plus MIPS er ideel for aktive mennesker og for daglig bruk. Hjelmen fungerer like godt på elsykkel, som på bysykkel. MRAS strammesystem for høy komfort. Voksen.', 10, 1, 1),
('Hjelm', 'Tilgjengelig', 'Groove Plus MIPS er ideel for aktive mennesker og for daglig bruk. Hjelmen fungerer like godt på elsykkel, som på bysykkel. MRAS strammesystem for høy komfort. Voksen.', 10, 1, 1),
('Hjelm', 'Tilgjengelig', 'Aerodynamisk landeveishjelm med 360-graders BOA strammesystem og MIPS. Lav vekt og høy komfort. Sitter godt og sikkert på alle hodefasonger. Vekt 300 gram. Voksen.', 8, 1, 1),
('Hjelm', 'Tilgjengelig', 'Aerodynamisk landeveishjelm med 360-graders BOA strammesystem og MIPS. Lav vekt og høy komfort. Sitter godt og sikkert på alle hodefasonger. Vekt 300 gram. Voksen.', 8, 1, 1),
('Hjelm', 'Tilgjengelig', 'Aerodynamisk landeveishjelm med 360-graders BOA strammesystem og MIPS. Lav vekt og høy komfort. Sitter godt og sikkert på alle hodefasonger. Vekt 300 gram. Voksen.', 8, 1, 1),
('Hjelm', 'Tilgjengelig', 'Aerodynamisk landeveishjelm med 360-graders BOA strammesystem og MIPS. Lav vekt og høy komfort. Sitter godt og sikkert på alle hodefasonger. Vekt 300 gram. Voksen.', 8, 1, 1),
('Hjelm', 'Tilgjengelig', 'Verdens raskeste og mest aerodynamiske tempohjelm. Designet av aerodynamikk-guru John Cobb.  Voksen.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Verdens raskeste og mest aerodynamiske tempohjelm. Designet av aerodynamikk-guru John Cobb.  Voksen.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Verdens letteste sykkelhjelm, med knallgod komfort og ventilasjon. Dobbeltskall in-mold med Ultralight-teknologi og 22 lufteventiler. Topp racinghjelm med uslåelige kvaliteter, som gjør at du yter best når det gjelder. Voksen.', 9, 1, 1),
('Hjelm', 'Tilgjengelig', 'Verdens letteste sykkelhjelm, med knallgod komfort og ventilasjon. Dobbeltskall in-mold med Ultralight-teknologi og 22 lufteventiler. Topp racinghjelm med uslåelige kvaliteter, som gjør at du yter best når det gjelder. Voksen.', 9, 1, 1),
('Hjelm', 'Tilgjengelig', 'Verdens letteste sykkelhjelm, med knallgod komfort og ventilasjon. Dobbeltskall in-mold med Ultralight-teknologi og 22 lufteventiler. Topp racinghjelm med uslåelige kvaliteter, som gjør at du yter best når det gjelder. Voksen.', 9, 1, 1),
('Hjelm', 'Tilgjengelig', 'Challenger har integrert feste for GoPro-kamera. Hjelmen festes ved hjelp av en magnetlås, som lukkes automatisk, og som enkelt kan åpnes med én hånd, også med hansker. Voksen.\n', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Challenger har integrert feste for GoPro-kamera. Hjelmen festes ved hjelp av en magnetlås, som lukkes automatisk, og som enkelt kan åpnes med én hånd, også med hansker. Voksen.\n', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Urban hjelm med integrert skygge. Ytterskall i ABS-plast, EPS-innmat. CE-godkjent for sykkel og skateboard. Sink Fit gir lav profil og økt sikkerhet. Voksen.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Urban hjelm med integrert skygge. Ytterskall i ABS-plast, EPS-innmat. CE-godkjent for sykkel og skateboard. Sink Fit gir lav profil og økt sikkerhet. Voksen.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Urban hjelm med integrert skygge. Ytterskall i ABS-plast, EPS-innmat. CE-godkjent for sykkel og skateboard. Sink Fit gir lav profil og økt sikkerhet. Voksen.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Urban hjelm med integrert skygge. Ytterskall i ABS-plast, EPS-innmat. CE-godkjent for sykkel og skateboard. Sink Fit gir lav profil og økt sikkerhet. Voksen.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Stisyklingshjelm for barn, som dekker bakhodet veldig godt. En sikker, lett og komfortabel hjelm med morsomt design. Hero har et integrert strammesystem som gjør at hjelmen sitter veldig godt under sykling. Barn.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Stisyklingshjelm for barn, som dekker bakhodet veldig godt. En sikker, lett og komfortabel hjelm med morsomt design. Hero har et integrert strammesystem som gjør at hjelmen sitter veldig godt under sykling. Barn.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Stisyklingshjelm for barn, som dekker bakhodet veldig godt. En sikker, lett og komfortabel hjelm med morsomt design. Hero har et integrert strammesystem som gjør at hjelmen sitter veldig godt under sykling. Barn.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Stisyklingshjelm for barn, som dekker bakhodet veldig godt. En sikker, lett og komfortabel hjelm med morsomt design. Hero har et integrert strammesystem som gjør at hjelmen sitter veldig godt under sykling. Barn.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Stisyklingshjelm for barn, som dekker bakhodet veldig godt. En sikker, lett og komfortabel hjelm med morsomt design. Hero har et integrert strammesystem som gjør at hjelmen sitter veldig godt under sykling. Barn.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Stisyklingshjelm for barn, som dekker bakhodet veldig godt. En sikker, lett og komfortabel hjelm med morsomt design. Hero har et integrert strammesystem som gjør at hjelmen sitter veldig godt under sykling. Barn.', 5, 1, 1),
('Hjelm', 'Tilgjengelig', 'Trygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpningrygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpninger. Insektnett. Integrert baklys i nakken. Vekt 220 gram. Barn.', 6, 1, 1),
('Hjelm', 'Tilgjengelig', 'Trygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpningrygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpninger. Insektnett. Integrert baklys i nakken. Vekt 220 gram. Barn.', 6, 1, 1),
('Hjelm', 'Tilgjengelig', 'Trygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpningrygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpninger. Insektnett. Integrert baklys i nakken. Vekt 220 gram. Barn.', 6, 1, 1),
('Hjelm', 'Tilgjengelig', 'Trygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpningrygg barnehjelm, lett og behagelig. Enkel tilpassing med strammehjul bak. Flere ventilasjonsåpninger. Insektnett. Integrert baklys i nakken. Vekt 220 gram. Barn.', 6, 1, 1),
('Sykkelveske', 'Tilgjengelig', 'Styrebag for oppbevaring og bruk av smarttelefon m.m. Passer telefoner på opptil 5,3\'\'. Med plass til småting, som energibarer, nøkler, penger eller annet.', 7, 1, 1),
('Sykkelveske', 'Tilgjengelig', 'Styrebag for oppbevaring og bruk av smarttelefon m.m. Passer telefoner på opptil 5,3\'\'. Med plass til småting, som energibarer, nøkler, penger eller annet.', 7, 1, 1),
('Sykkelveske', 'Tilgjengelig', 'Styrebag for oppbevaring og bruk av smarttelefon m.m. Passer telefoner på opptil 5,3\'\'. Med plass til småting, som energibarer, nøkler, penger eller annet.', 7, 1, 1),
('Sykkelveske', 'Tilgjengelig', 'Styrebag for oppbevaring og bruk av smarttelefon m.m. Passer telefoner på opptil 5,3\'\'. Med plass til småting, som energibarer, nøkler, penger eller annet.', 7, 1, 1),
('Sykkelveske', 'Tilgjengelig', 'Sykkelkoffert i solid utførelse, for inntil 29\" landeveis-, triatlon- eller terrengsykkel. Sterk alu.-ramme. Avtakbart lokk for enklere pakking. Vekt 16 kg.', 15, 1, 1),
('Sykkelveske', 'Tilgjengelig', 'Sykkelkoffert i solid utførelse, for inntil 29\" landeveis-, triatlon- eller terrengsykkel. Sterk alu.-ramme. Avtakbart lokk for enklere pakking. Vekt 16 kg.', 15, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Vanntett styrebag som kan bæres som skulderveske. PVC-fritt stoff, klimanøytralt produsert. Lukkes med to klikklåser.', 7, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Vanntett styrebag som kan bæres som skulderveske. PVC-fritt stoff, klimanøytralt produsert. Lukkes med to klikklåser.', 7, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Vanntett styrebag som kan bæres som skulderveske. PVC-fritt stoff, klimanøytralt produsert. Lukkes med to klikklåser.', 7, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Vanntett styrebag som kan bæres som skulderveske. PVC-fritt stoff, klimanøytralt produsert. Lukkes med to klikklåser.', 7, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Funksjonell seteveske med ekspanderbart volum (med glidelås). Rommelig seteveske som har plass til både energibar, ekstra slange, verktøy og dekkspaker.', 5, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Funksjonell seteveske med ekspanderbart volum (med glidelås). Rommelig seteveske som har plass til både energibar, ekstra slange, verktøy og dekkspaker.', 5, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Funksjonell seteveske med ekspanderbart volum (med glidelås). Rommelig seteveske som har plass til både energibar, ekstra slange, verktøy og dekkspaker.', 5, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Funksjonell seteveske med ekspanderbart volum (med glidelås). Rommelig seteveske som har plass til både energibar, ekstra slange, verktøy og dekkspaker.', 5, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Seteveske for montering under sykkelsetet. Holder verktøy og småting godt organisert, tørt og enkelt tilgjengelig når du måtte trenge det.', 4, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Seteveske for montering under sykkelsetet. Holder verktøy og småting godt organisert, tørt og enkelt tilgjengelig når du måtte trenge det.', 4, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Seteveske for montering under sykkelsetet. Holder verktøy og småting godt organisert, tørt og enkelt tilgjengelig når du måtte trenge det.', 4, 1, 1),
( 'Sykkelveske', 'Tilgjengelig', 'Seteveske for montering under sykkelsetet. Holder verktøy og småting godt organisert, tørt og enkelt tilgjengelig når du måtte trenge det.', 4, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Patentert bagasjebærer og festesystem for sykkelbager, som fungerer på de fleste sykler. Systemet kan monteres på alt fra fulldempere til pendlersykler.', 8, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Patentert bagasjebærer og festesystem for sykkelbager, som fungerer på de fleste sykler. Systemet kan monteres på alt fra fulldempere til pendlersykler.', 8, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Patentert bagasjebærer og festesystem for sykkelbager, som fungerer på de fleste sykler. Systemet kan monteres på alt fra fulldempere til pendlersykler.', 8, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Patentert bagasjebærer og festesystem for sykkelbager, som fungerer på de fleste sykler. Systemet kan monteres på alt fra fulldempere til pendlersykler.', 8, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Klassisk utseende, bagasjebrett i aluminium, med runde rør. Designet for å passe sykler med skivebremser.', 6, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Klassisk utseende, bagasjebrett i aluminium, med runde rør. Designet for å passe sykler med skivebremser.', 6, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Klassisk utseende, bagasjebrett i aluminium, med runde rør. Designet for å passe sykler med skivebremser.', 6, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Klassisk utseende, bagasjebrett i aluminium, med runde rør. Designet for å passe sykler med skivebremser.', 6, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Klassisk utseende, bagasjebrett i aluminium, med runde rør. Designet for å passe sykler med skivebremser.', 6, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Klassisk utseende, bagasjebrett i aluminium, med runde rør. Designet for å passe sykler med skivebremser.', 6, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
( 'Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
('Bagasjebrett', 'Tilgjengelig', 'Et lettvekts bagasjebrett for montering på setepinnen. Passer setetpinner med diameter fra 22,2 til 31,8 mm. Utforinger følger med.', 5, 1, 1),
('Vogn', 'Tilgjengelig', 'Robust sykkelhenger for sikre og behagelige turer. Kan enkelt gjøres om til sportsvogn når man kommer fram, med det medfølgende nesehjulet. Vekt 12 kg. For å frakte barn eller utstyr.', 15, 1, 1),
('Vogn', 'Tilgjengelig', 'Robust sykkelhenger for sikre og behagelige turer. Kan enkelt gjøres om til sportsvogn når man kommer fram, med det medfølgende nesehjulet. Vekt 12 kg. For å frakte barn eller utstyr.', 15, 1, 1),
('Vogn', 'Tilgjengelig', 'Robust sykkelhenger for sikre og behagelige turer. Kan enkelt gjøres om til sportsvogn når man kommer fram, med det medfølgende nesehjulet. Vekt 12 kg. For å frakte barn eller utstyr.', 15, 1, 1),
('Vogn', 'Tilgjengelig', 'Robust sykkelhenger for sikre og behagelige turer. Kan enkelt gjøres om til sportsvogn når man kommer fram, med det medfølgende nesehjulet. Vekt 12 kg. For å frakte barn eller utstyr.', 15, 1, 1),
('Vogn', 'Tilgjengelig', 'Robust sykkelhenger for sikre og behagelige turer. Kan enkelt gjøres om til sportsvogn når man kommer fram, med det medfølgende nesehjulet. Vekt 12 kg. For å frakte barn eller utstyr.', 15, 1, 1),
('Vogn', 'Tilgjengelig', 'Solid etthjuls sykkelhenger med gjennomtenkt design, for sykkelcamping, langturer og stisykling. Justerbar dragbredde, innebygget demping. Vekt 9,74 kg. For å frakte barn eller utstyr.', 20, 1, 1),
('Vogn', 'Tilgjengelig', 'Solid etthjuls sykkelhenger med gjennomtenkt design, for sykkelcamping, langturer og stisykling. Justerbar dragbredde, innebygget demping. Vekt 9,74 kg. For å frakte barn eller utstyr.', 20, 1, 1),
('Vogn', 'Tilgjengelig', 'Solid etthjuls sykkelhenger med gjennomtenkt design, for sykkelcamping, langturer og stisykling. Justerbar dragbredde, innebygget demping. Vekt 9,74 kg. For å frakte barn eller utstyr.', 20, 1, 1),
('Vogn', 'Tilgjengelig', 'Solid etthjuls sykkelhenger med gjennomtenkt design, for sykkelcamping, langturer og stisykling. Justerbar dragbredde, innebygget demping. Vekt 9,74 kg. For å frakte barn eller utstyr.', 20, 1, 1),
('Vogn', 'Tilgjengelig', 'Solid etthjuls sykkelhenger med gjennomtenkt design, for sykkelcamping, langturer og stisykling. Justerbar dragbredde, innebygget demping. Vekt 9,74 kg. For å frakte barn eller utstyr.', 20, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
('Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
( 'Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1),
( 'Barnesete', 'Tilgjengelig', 'Lett, sikkert bakmontert barnesete for sykkel. Smart design for turer rundt i og i nærheten av byen. Universalbrakett, passer alle sykler med bagasjebærer.', 10, 1, 1);
